 using hostname.

[code language="java"]
node {

    environment {
        registry = "alexseedkou/docker-test"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/alexseedkou/sample-spring-microservices.git', credentialsId: 'alexseedkou', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('account-service') {
                dockerImage = docker.build registry + "microservice:$BUILD_NUMBER"
                // app.push()
            }
        }

        stage('Deploy Image') {
            docker.withRegistry('', registryCredential) {
                dockerImage.push();
            }
        }

        // stage ('Run') {
        //     docker.image("localhost:5000/account-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        // }

        // stage ('Final') {
        //     build job: 'customer-service-pipeline', wait: false
        // }      

    }

}